# Customer Churn Prediction:Analysis

Import Libraries and Load Dataset

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
df = pd.read_csv(r"C:\Users\navin\Downloads\archive (8).zip")
print(df)

     CustomerID  Age  Gender  Tenure  MonthlyCharges    ContractType  \
0             1   49    Male       4           88.35  Month-to-Month
1             2   43    Male       0           36.67  Month-to-Month
2             3   51  Female       2           63.79  Month-to-Month
3             4   60  Female       8          102.34        One-Year
4             5   42    Male      32           69.01  Month-to-Month
..          ...  ...     ...     ...             ...             ...
995         996   42    Male      41           37.14  Month-to-Month
996         997   62    Male       9           80.93  Month-to-Month
997         998   51  Female      15          111.72  Month-to-Month
998         999   39    Male      68           65.67        One-Year
999        1000   50    Male       1           56.67  Month-to-Month

    InternetService  TotalCharges TechSupport Churn
0       Fiber Optic        353.40         Yes   Yes
1       Fiber Optic          0.00         Yes   Yes
2       Fiber Optic        127.58          No   Yes
3               DSL        818.72         Yes   Yes
4              None       2208.32          No   Yes
..              ...           ...         ...   ...
995     Fiber Optic       1522.74         Yes   Yes
996            None        728.37          No   Yes
997     Fiber Optic       1675.80         Yes   Yes
998            None       4465.56          No   Yes
999            None         56.67          No   Yes

[1000 rows x 10 columns]

In [2]:
df.head()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,2,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,3,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,4,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,5,42,Male,32,69.01,Month-to-Month,None,2208.32,No,Yes

In [3]:
df.shape

(1000, 10)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1000 non-null   int64
 1   Age              1000 non-null   int64
 2   Gender           1000 non-null   object
 3   Tenure           1000 non-null   int64
 4   MonthlyCharges   1000 non-null   float64
 5   ContractType     1000 non-null   object
 6   InternetService  1000 non-null   object
 7   TotalCharges     1000 non-null   float64
 8   TechSupport      1000 non-null   object
 9   Churn            1000 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 78.2+ KB

In [8]:
df.isnull().sum()

CustomerID         0
Age                0
Gender             0
Tenure             0
MonthlyCharges     0
ContractType       0
InternetService    0
TotalCharges       0
TechSupport        0
Churn              0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [11]:
df = df.drop("CustomerID", axis=1)

In [12]:
df.head()

,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.40,Yes,Yes
1,43,Male,0,36.67,Month-to-Month,Fiber Optic,0.00,Yes,Yes
2,51,Female,2,63.79,Month-to-Month,Fiber Optic,127.58,No,Yes
3,60,Female,8,102.34,One-Year,DSL,818.72,Yes,Yes
4,42,Male,32,69.01,Month-to-Month,None,2208.32,No,Yes

In [13]:
df.dtypes

Age                  int64
Gender              object
Tenure               int64
MonthlyCharges     float64
ContractType        object
InternetService     object
TotalCharges       float64
TechSupport         object
Churn               object
dtype: object

In [14]:
numeric_features = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = df.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numerical features:")
print(numeric_features)

print("\nCategorical features:")
print(categorical_features)

Numerical features:
['Age', 'Tenure', 'MonthlyCharges', 'TotalCharges']

Categorical features:
['Gender', 'ContractType', 'InternetService', 'TechSupport', 'Churn']

In [15]:
df["InternetService"] = df["InternetService"].fillna(
    df["InternetService"].mode()[0]
)

In [16]:
df.isnull().sum()

Age                0
Gender             0
Tenure             0
MonthlyCharges     0
ContractType       0
InternetService    0
TotalCharges       0
TechSupport        0
Churn              0
dtype: int64

In [18]:
#Identify Categorical Columns
df.select_dtypes(include='object').columns

Index(['Gender', 'ContractType', 'InternetService', 'TechSupport', 'Churn'], dtype='object')

In [19]:
#Encode Categorical Variables
#Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])
df['ContractType'] = le.fit_transform(df['ContractType'])
df['InternetService'] = le.fit_transform(df['InternetService'])
df['TechSupport'] = le.fit_transform(df['TechSupport'])
df['Churn'] = le.fit_transform(df['Churn'])

In [20]:
df.head()

,Age,Gender,Tenure,MonthlyCharges,ContractType,InternetService,TotalCharges,TechSupport,Churn
0,49,1,4,88.35,0,1,353.40,1,1
1,43,1,0,36.67,0,1,0.00,1,1
2,51,0,2,63.79,0,1,127.58,0,1
3,60,0,8,102.34,1,0,818.72,1,1
4,42,1,32,69.01,0,2,2208.32,0,1

Features and Target

In [21]:
#Feature variable x
X = df.drop("Churn", axis=1)

In [23]:
#Target variables y
y = df["Churn"]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,      # 20% for testing, 80% for training
    random_state=42,    # Ensures reproducibility
    stratify=y          # Maintains class distribution
)

In [25]:
#check shape
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (800, 8)
X_test shape: (200, 8)
y_train shape: (800,)
y_test shape: (200,)

Feature Scaling

In [26]:
scaler = StandardScaler()   #Create a Scaler Object
X_train_scaled = scaler.fit_transform(X_train)   #Fit and Transform Training Data
X_test_scaled = scaler.transform(X_test)    #Transform Testing Data

   Model Training

Logistic Regression

In [27]:
from sklearn.linear_model import LogisticRegression

# Create model
lr_model = LogisticRegression(random_state=42)

# Train model
lr_model.fit(X_train_scaled, y_train)

# Predict
y_pred_lr = lr_model.predict(X_test_scaled)

In [28]:
from sklearn.metrics import accuracy_score

print("Logistic Regression Accuracy:",
      accuracy_score(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.91

Random Forest

In [31]:
from sklearn.ensemble import RandomForestClassifier

# Create model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train model
rf_model.fit(X_train, y_train)

# Predict
y_pred_rf = rf_model.predict(X_test)

In [32]:
print("Random Forest Accuracy:",
      accuracy_score(y_test, y_pred_rf))

Random Forest Accuracy: 1.0

Support Vector Machine (SVM)

In [33]:
from sklearn.svm import SVC

# Create model
svm_model = SVC(
    kernel='rbf',
    random_state=42
)

# Train model
svm_model.fit(X_train_scaled, y_train)

# Predict
y_pred_svm = svm_model.predict(X_test_scaled)

In [34]:
print("SVM Accuracy:",
      accuracy_score(y_test, y_pred_svm))

SVM Accuracy: 0.975

XGBoost (Extreme Gradient Boosting)

In [36]:
from xgboost import XGBClassifier

# Create model
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

# Train model
xgb_model.fit(X_train, y_train)

# Predict
y_pred_xgb = xgb_model.predict(X_test)

In [37]:
print("XGBoost Accuracy:",
      accuracy_score(y_test, y_pred_xgb))

XGBoost Accuracy: 1.0

Cross validation

In [38]:
from sklearn.model_selection import cross_val_score

# Define models
models = {
    "Logistic Regression": LogisticRegression(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "SVM": SVC(kernel='rbf', random_state=42),
    "XGBoost": XGBClassifier(random_state=42)
}

# Perform 5-Fold Cross Validation
cv_results = {}

for name, model in models.items():
    scores = cross_val_score(
        model,
        X_train_scaled,
        y_train,
        cv=5,
        scoring='accuracy'
    )
    
    cv_results[name] = scores.mean()
    
    print(f"{name}")
    print("CV Scores:", scores)
    print("Average CV Accuracy: {:.4f}".format(scores.mean()))
    print("-"*50)

Logistic Regression
CV Scores: [0.9     0.8875  0.9     0.94375 0.94375]
Average CV Accuracy: 0.9150
--------------------------------------------------
Random Forest
CV Scores: [0.9875 1.     1.     1.     1.    ]
Average CV Accuracy: 0.9975
--------------------------------------------------
SVM
CV Scores: [0.95625 0.96875 0.975   0.94375 0.96875]
Average CV Accuracy: 0.9625
--------------------------------------------------
XGBoost
CV Scores: [0.9875 1.     1.     1.     1.    ]
Average CV Accuracy: 0.9975
--------------------------------------------------

Hyperparameter Tuning

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

# Create Logistic Regression model
lr = LogisticRegression(random_state=42)

# Define hyperparameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}

# Perform Grid Search with 5-fold Cross Validation
grid_search = GridSearchCV(
    estimator=lr,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

# Fit Grid Search
grid_search.fit(X_train_scaled, y_train)

# Best model
best_lr = grid_search.best_estimator_

# Make predictions
y_pred = best_lr.predict(X_test_scaled)

# Print results
print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest Cross Validation Accuracy:")
print(grid_search.best_score_)

print("\nTest Accuracy:")
print(accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Best Parameters:
{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

Best Cross Validation Accuracy:
0.92125

Test Accuracy:
0.925

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.35      0.52        23
           1       0.92      1.00      0.96       177

    accuracy                           0.93       200
   macro avg       0.96      0.67      0.74       200
weighted avg       0.93      0.93      0.91       200

Final Prediction

In [40]:
# Final prediction on test set
y_pred = best_lr.predict(X_test_scaled)

print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1]

Classification Report

In [41]:
from sklearn.metrics import classification_report

# Generate classification report
report = classification_report(y_test, y_pred)

# Print report
print("Classification Report:")
print(report)

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.35      0.52        23
           1       0.92      1.00      0.96       177

    accuracy                           0.93       200
   macro avg       0.96      0.67      0.74       200
weighted avg       0.93      0.93      0.91       200

In [42]:
#logistic code
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Make predictions
y_pred = best_lr.predict(X_test_scaled)

# Accuracy
print("Accuracy Score:")
print(accuracy_score(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy Score:
0.925

Confusion Matrix:
[[  8  15]
 [  0 177]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.35      0.52        23
           1       0.92      1.00      0.96       177

    accuracy                           0.93       200
   macro avg       0.96      0.67      0.74       200
weighted avg       0.93      0.93      0.91       200